serviceAccount: "projects/ai-chatbot-training/serviceAccounts/ai-chatbot-training@appspot.gserviceaccount.com"
logsBucket: "gs://ai-chatbot-training.appspot.com"
options:
  logging: GCS_ONLY

steps:
  # Backend Deployment
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "server/app.yaml"]

timeout: "1600s"
