serviceAccount: "projects/ai-chatbot-training/serviceAccounts/ai-chatbot-training@appspot.gserviceaccount.com"
logsBucket: "gs://ai-chatbot-training.appspot.com"
options:
  logging: GCS_ONLY

steps:
  # Building Docker Image
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
      - "--dockerfile=Dockerfile"
      - "--context=dir://."
      - "--destination=gcr.io/ai-chatbot-training/a-ware-demo-server:latest"

  # Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "a-ware-demo-server",
        "--image",
        "gcr.io/ai-chatbot-training/a-ware-demo-server:latest",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--service-account",
        "ai-chatbot-training@appspot.gserviceaccount.com",
      ]

timeout: "1600s"
