# Use the official lightweight Node.js image.
FROM node:18-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install production dependencies.
RUN npm install --only=production

# Copy the rest of your application's code
COPY . .

# Set the environment to production
ENV NODE_ENV production

# Your app must listen on the port defined by the PORT environment variable.
EXPOSE 8080

CMD ["node", "api.js"]
